### ISSUE TITLE
main process `Store` shouldn't use default values.

### ISSUE THREAD

**Issue by liaofranku** [liao-frank/channel-points-controller#4]
The current `Store` tool requires a default value to be set. Usually, it's an object with empty field.

In the frontend, it means I have to check if a field on the object exists, rather than checking the existence of the object, which isn't intuitive.

i.e I want to do `if (user)` to see if there is a user, not `if (user.id)` to see if there is a user.

We should check if the `electron-store` library allows setting the values to undefined, then change the `Store` tool.

**Comment by kev-cai** [comment]
it done
